services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  site:
    image: nginx:alpine
    container_name: site
    restart: always
    volumes:
      - "./site:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`SEU_DOMINIO.com`)"
      - "traefik.http.services.site.loadbalancer.server.port=80"
